version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=dicra
  api:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - "/Users/amjad/Desktop/PERSONAL/DiCRA-API:/app"
volumes:
  postgres_data:
