<<<<<<< HEAD
name: API CI CD
=======
name: Deploy DiCRA to API Server
>>>>>>> a699acbeeb32e859808b4c1eea35fb77ac6ee5b2
on:
  push:
    paths:
      - 'src/api/**'
    branches: 
      - develop
jobs:
  Deploy:
    runs-on: [self-hosted,Linux,X64,developmentserver]
    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - name: 'Create alembic.ini and config.ini'
      env:
        SECRETS: ${{ secrets.API_SECRETS }}
      run: |
        mkdir config
        echo -e $SECRETS >> config/config.ini
        sed 's/^sqlalchemy.url =.*/sqlalchemy.url =${{ secrets.CONNECTION_STRING }}/' alembic.ini > updatedalembic.ini
        sudo rm alembic.ini
        mv updatedalembic.ini alembic.ini
        mkdir static
        mkdir temp_files
        sudo systemctl restart gunicorn.service