name: Deploy DiCRA to API Server
on:
  push:
    paths:
      - 'src/api/**'
    branches: 
      - develop
jobs:
  Deploy:
    runs-on: [self-hosted,Linux,X64,developmentserver]
    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - name: 'Create alembic.ini and config.ini'
      env:
        SECRETS: ${{ secrets.API_SECRETS }}
        CONNECTIONSTRING: ${{ secrets.CONNECTION_STRING }}
      run: |
        cd /home/azureuser/actions-runner/undp-api/dicra/dicra/src/api
        mkdir config
        echo -e $SECRETS >> config/config.ini
        mkdir static
        mkdir temp_files
        sed 's/^sqlalchemy.url =.*/sqlalchemy.url =$CONNECTIONSTRING/' alembic.ini > updatedalembic.ini
        sudo rm alembic.ini
        mv updatedalembic.ini alembic.ini
    - name: 'Restart gunicorn service'
      run: sudo systemctl restart gunicorn.service